env:
  browser: true
  node: true,
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
overrides: [
    {
      "files": ["**/*.js?(x)"],
      "rules": {
        "react/no-unescaped-entities": "off",
        "react/display-name": "off",
        "react/prop-types": "off",
      }
  }
]
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-duplicate-imports:
    - error
  
